name: mlagentbench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - cpython=3.10.19=py310hd8ed1ab_3
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.9=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_5
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.3=h5347b49_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pillow=9.4.0=py310h023d228_1
  - pip=26.0=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=hd12c33a_0_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.10.2=pyh332efcf_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.7.0=h924138e_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.77.1
      - anyio==4.12.1
      - async-timeout==4.0.3
      - charset-normalizer==3.1.0
      - click==8.3.1
      - dacite==1.9.2
      - distro==1.9.0
      - docstring-parser==0.17.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - fsspec==2026.1.0
      - greenlet==3.3.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.0
      - jax==0.4.6
      - jaxlib==0.4.6+cuda11.cudnn86
      - jiter==0.13.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-anthropic==1.3.1
      - langchain-classic==1.0.1
      - langchain-core==1.2.8
      - langchain-text-splitters==1.1.0
      - langsmith==0.6.8
      - mlagentbench==0.1
      - mypy-extensions==1.1.0
      - openai==2.16.0
      - opt-einsum==3.4.0
      - orjson==3.11.7
      - pandas==2.3.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyg-lib==0.4.0+pt20cu117
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - regex==2026.1.15
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - scipy==1.15.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.46
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - torch-cluster==1.6.3+pt20cu117
      - torch-scatter==2.1.2+pt20cu117
      - torch-sparse==0.6.18+pt20cu117
      - tqdm==4.67.3
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-inspect==0.8.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uuid-utils==0.14.0
      - xxhash==3.6.0
prefix: /home/mayank/miniconda3/envs/mlagentbench
